Rakefile

Running bin/rake now runs rubocop and the specs. 
As we run rubocop on Circle CI this can help to prevent sending up jobs that fail at the first hurdle.
Also keeps it in line with our other repos.

add rubocop to rakefile

---

Gemfile.lock

I had not realised that it updated the Gemfile but did not run
bundle install, there was a disconnect between the two
This ensures the installed gems matches the Gemfile

Tech-Debt: Update gems after Snyk PR

---

app/models/default_cost_limitation.rb
app/models/proceeding_type.rb
db/migrate/20210930074336_create_default_cost_limitations.rb
db/populators/proceeding_type_populator.rb
db/schema.rb
spec/models/default_cost_limitation_spec.rb
spec/models/proceeding_type_spec.rb

**What**
Add default costs and effective dates to proceeding types 
https://dsdmoj.atlassian.net/browse/AP-2451
**Why**
For LFA to become the source of truth for default costs and their effective dates
**How**
(Copying the current functionality from apply)
Created a new model default_cost_limitations
Populated this with data for substantive and delegated_functions proceeding_types (before and after 13/9/2021)
Added default_cost_limitation_delegated_functions and default_cost_limitation_substantive functions to proceeding_type model

Ap 2451 add default cost limitations

---

Gemfile
Gemfile.lock
app/controllers/proceeding_types/searches_controller.rb
app/models/proceeding_type.rb
app/services/proceeding_type_full_text_search.rb
config/initializers/cors.rb
config/routes.rb
spec/requests/proceeding_types/searches_spec.rb
spec/services/proceeding_type_full_text_search_spec.rb

Addresses two issues:
This allows Apply to request all proceeding types
It may end up getting deprecated in future but for now it will allow like-for-like replacement with the way Apply processes it's internal function
As I used the endpoint from apply it made more sense to rename it to excluded_codes as that is what we are expecting and using

AP-2465: ProceedingType search update

---

app/controllers/proceeding_types_controller.rb
app/services/proceeding_type_populator.rb
app/services/proceeding_type_service.rb
db/migrate/20211005102214_add_searchable_fields_to_proceeding_types.rb
db/migrate/20211130102438_add_name_to_proceeding_types.rb
db/schema.rb
db/seed_data/proceeding_types.yml
spec/requests/proceeding_types_spec.rb
spec/services/proceeding_type_service_spec.rb

Apply uses the proceeding type name in a number of places (`proceedings_by_name` method on the LegalAidApplication model, for example. Currently this data isn't held in LFA.
This change
* adds the field to the model and updates seed data and populator so that the names is held in LFA.
* updates the proceeding type service and controller so that the name is returned for requests to the `proceeding_type` endpoint.

Add name to proceeding_type

---

db/migrate/20211130102438_add_name_to_proceeding_types.rb
db/schema.rb

Lack of a default name is causing issues when running migrations. This
adds a default name to existing records which will be overwritten when
data is seeded.

Set default name on proceeding_types

---

.circleci/config.yml

The CircleCI Slack Orb needs to be updated from `v3.4.2` to the latest version (`v4.4.4`). This is a breaking change and requires some reconfiguration to allow Slack notifications to continue to work:
* `SLACK_DEFAULT_CHANNE` and `SLACK_ACCESS_TOKEN` environment variables configured in CircleCI.
* CircleCI Slack Orb upgraded to `v4.4.4` in `.circleci/config.yml`.
* `hold_production_notification` command replaced with customised `slack/on-hold` command.
* Notifications for any failed workflow step enabled.

AP-2606 Update CircleCI Slack orb

---

app/services/proceeding_type_full_text_search.rb
spec/requests/merits_tasks_spec.rb
spec/services/merits_task_service_spec.rb
spec/services/proceeding_type_service_spec.rb

While assessing the Rails 7 PR for failures I did some investigating.
There were two issues, an error message change and a nested array issue in the full-text search
This PR addresses the two issues in Rails 6x in the hope that it will make the Rails 7 transition easier!
* In the full-text search, remove the nested array and replace it with a single-level array of variable to be searched for, without nil accompanying it
* The finder_method now returns an extended error message, see [this response](rails/rails#38956) The current method should currently fail in Rails 6.x (but doesn't) but it is definitely [failing in Rails 7+](https://github.com/ministryofjustice/legal-framework-api/pull/313)

Tech debt: Prepare for rails 7

---

deploy/helm/templates/ingress.yaml

Updates i`ngress.yaml` to use `networking.k8s.io/v1` as a result of moving to the live cluster. This reconfigures the ingress using the new syntax.

AP-2771 Update ingress.yaml to use networking.k8s.io/v1

---

Gemfile.lock

Running any bundle command using the current version causes the following warning to be displayed:
```
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, s
pell_checker)' instead.
```
This bumps bundler to the newest version which resolves this.

Update bundler to v2.3.5

---

.rubocop_todo.yml
app/controllers/merits_tasks_controller.rb
app/controllers/proceeding_types/searches_controller.rb
app/controllers/proceeding_types/threshold_waivers_controller.rb
app/controllers/proceeding_types_controller.rb
app/controllers/status_controller.rb
app/models/default_cost_limitation.rb
app/models/proceeding_type.rb
app/services/merits_task_service.rb
app/services/proceeding_type_service.rb
app/services/threshold_waiver_service.rb
config/environments/development.rb
config/environments/test.rb
db/populators/proceeding_type_scope_limitations_populator.rb
spec/requests/merits_tasks_spec.rb
spec/requests/proceeding_types/searches_spec.rb
spec/requests/proceeding_types/threshold_waivers_spec.rb
spec/requests/proceeding_types_spec.rb
spec/services/merits_task_service_spec.rb
spec/services/proceeding_type_service_spec.rb
spec/services/threshold_waiver_service_spec.rb

Removes the `Style/TrailingCommaInHashLiteral` and `Style/WordArray` cops from the `.rubocop_todo` file and fixes resulting offences.

Remove more rubocop todos

---

Gemfile

The `default` Rake task (i.e. running `bundle exec rake`) is set up to run rubocop and rspec sequentially however stops after rubocop completes. This is because the `rspec-rails` gem only exists in the `:test` group in the Gemfile.
This change moves the gem to the `:development, :test` group where it can be accessed by Rake and run correctly.
- You should have looked at the diff against main and ensured …

TechDebt: Move rspec-rails gem to fix default Rake task

---

bin/uat_deploy

[Link to story](https://dsdmoj.atlassian.net/jira/software/c/projects/AP/boards/233?modal=detail&selectedIssue=AP-2859)
UAT deployments fail if GitHub branch names contain a capital letter; down case branch names in deploy script to prevent this. …

AP-2859-allow-uppercase-in-branch-names

---

README.md
app/controllers/proceeding_types/searches_controller.rb
spec/requests/proceeding_types/searches_spec.rb

This was created as /search originally but then renamed, the
documentation was not updated to match

Fix: Update the references to the search endpoint

---

db/seeds.rb

Internally this runs ProceedingTypePopulator.call and ensures the`textsearchable` field is populated and allow the search endpoints to run

Fix: ProceedingType populator called with seeds

---

app/services/proceeding_type_service.rb
spec/requests/proceeding_types_spec.rb
spec/services/proceeding_type_service_spec.rb

Expose service levels on proceeding type endpoint
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3078)
To enable consumers to use the associated service
levels per proceeding type.

[AP-3078] Expose service_levels on proceeding_type details

---

app/controllers/main_controller.rb
app/services/proceeding_type_service.rb
config/environments/test.rb
config/routes.rb
spec/requests/main_spec.rb
spec/requests/proceeding_types_spec.rb
spec/requests/status_spec.rb
spec/services/proceeding_type_service_spec.rb

This originally started as a ticket to set the default root path to `/api-docs`, but other issues became apparent:
- coverage wasn't reporting on files that weren't touched at all during testing
- the ordering of service levels in the response could change from test run to test run leading to flickering tests.
The following changes fix all the above
- set root route as 'main#index`
- create `MainController` with an index action that redirects to `/api-docs`
- set `eager_loading` to `false` for test environment so that `SimpleCov` reports on ALL files, not just the ones that are hit during testing
- Ensure service levels are added to the response in numerical order of service level number
- Change expected results to be in numeric order of service level
Before you ask people to review this …

Set /api-docs as root route

---

.github/workflows/delete-uat-release.yml

[Link to story](https://dsdmoj.atlassian.net/browse/AP-3184)
This uses `ministryofjustice/laa-civil-apply-delete-uat-release@v1.0.0` to allow us to
share the github action logic between all apply service components this.
This will render the circleci step redundant.
- You should have checked …

[AP-3184] Use remote github action to delete UAT release

---

app/controllers/client_involvement_types_controller.rb
app/models/client_involvement_type.rb
config/routes.rb
spec/factories/client_involvement_type.rb
spec/models/client_involvement_type_spec.rb
spec/requests/client_involvement_types_controller_spec.rb
spec/requests/swagger_docs/client_involvement_types_spec.rb
swagger/v1/swagger.yaml

[Link to story](https://dsdmoj.atlassian.net/browse/AP-3292)
Add the new Client Involvement Type endpoint (`/client_involvement_types`)
Update the model to allow the API to return data that is filtered to only the information needed
Add the swagger tests and update the documentation
- You …

AP-3292: Add the client involvement type api endpoint

---

spec/requests/swagger_docs/proceeding_type_defaults_spec.rb
swagger/v1/swagger.yaml

One of the variables was mis-named in the example

Fix: proceeding_type_defaults swagger

---

app/models/scope_limitation.rb
app/models/scope_limitation_user_input.rb
app/models/scope_user_input.rb
db/migrate/20220804111406_create_scope_user_inputs.rb
db/migrate/20220804112224_create_scope_limitation_user_inputs.rb
db/schema.rb
spec/factories/scope_limitations.rb
spec/factories/scope_user_inputs.rb
spec/models/scope_limitation_spec.rb
spec/models/scope_user_input_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-3381)
Some scope limitations have user input requirements.  This PR creates a table of user inputs definitaions, defining the name, the type of input and whether or not it is mandatory, and a many-to-many join table between scope and user inputs
- You should have looked at the diff against main and ensured that nothing unexpected is included in your …

AP-3381 Add Scope user Inputs table

---

Gemfile
Gemfile.lock
app/controllers/proceeding_type_scopes_controller.rb
app/services/proceeding_type_scopes_service.rb
app/validators/json_validator.rb
config/routes.rb
public/schemas/proceeding_type_scopes.json.erb
spec/requests/proceeding_type_defaults_controller_spec.rb
spec/requests/proceeding_type_scopes_controller_spec.rb
spec/requests/swagger_docs/proceeding_type_scopes_spec.rb
spec/services/proceeding_type_scopes_service_spec.rb
spec/validators/json_validator_spec.rb
swagger/v1/swagger.yaml

[Link to story](https://dsdmoj.atlassian.net/browse/AP-3351)
- implemented a new endpoint /proceeding_type_scopes. This returns level of service, and associated scope_limitations, for a given proceeding_type, client_involvement_type, service_level and delegated_functions_used.
- Implemented json_schema validation for the request payload, similar to that on CFE.
TODO
If we use the json_schema validation we should create a ticket to validate the payload on the /proceeding_type_defaults endpoint (as it is the same as for this endpoint)
- There should be no unnecessary whitespace changes. These make diffs …

Ap 3351 proceeding type scopes endpoint

---

deploy/helm/templates/ingress.yaml

[Link to story](https://dsdmoj.atlassian.net/browse/AP-3364)
Add ingressClassName as a standard, default, to the ingress template
We currently don't use modsec on this service so there is no need to
parametize it... yet!
- You should have checked that the commit messages say why the change …

AP-3364: Update ingress

---

app/models/scope_limitation.rb
app/models/scope_user_input.rb
app/models/service_level.rb
app/services/eligible_scopes_service.rb
app/services/proceeding_type_defaults_service.rb
app/services/proceeding_type_scopes_service.rb
config/eligible_scopes.yml
public/schemas/proceeding_type_defaults.json.erb
spec/requests/proceeding_type_defaults_controller_spec.rb
spec/requests/proceeding_type_scopes_controller_spec.rb
spec/requests/swagger_docs/proceeding_type_defaults_spec.rb
spec/services/eligible_scopes_service_spec.rb
spec/services/proceeding_type_defaults_service_spec.rb
spec/services/proceeding_type_scopes_service_spec.rb
swagger/v1/swagger.yaml

[Link to story](https://dsdmoj.atlassian.net/browse/AP-3407)
This is rebased of AP-3407.
The `proceeding_type_defaults` endpoint no longer takes service level as a parameter - it doesn't make sense as it's the default service level and default scope limitation that is returned as a response to this call.
The internal workings of this was also changed to use the `EligibleScopeService` as this uses the yaml config file which is the source of truth for full section 8, unlike the old join table which only has data relating to the section 8 proceedings that we already handle.
- There should be no …

AP-3407A  Alter proceeding_type_defaults to not take service level as param

---

db/populators/scope_limitations_populator.rb
spec/requests/proceeding_type_scopes_controller_spec.rb
spec/services/proceeding_type_scopes_service_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-3545)
Remove CV079 from the HEARING_DATE_CODES array.  This was added in error and, after consulting with the business analyst, it was agreed it should never have been included
- You should have checked that the commit messages say why …

AP-3545: Update ScopeLimitationsPopulator

---

app/services/questions_service.rb
db/populators/merits_task_populator.rb
db/seed_data/proceeding_type_merits_task.yml
spec/models/proceeding_type_spec.rb
spec/requests/civil_merits_questions_controller_swagger_spec.rb
spec/requests/merits_tasks_controller_swagger_spec.rb
spec/services/merits_task_service_spec.rb
spec/services/questions_service_spec.rb
swagger/v1/swagger.yaml

[Link to story](https://dsdmoj.atlassian.net/browse/AP-3571)
Update the proceeding_type_merits_task seed data with the new section 8 questions
Add new display rules into the QuestionService to handle the new changes
Update existing tests to ensure new rules are applied appropriately and are adding new tasks where needed
Update the swagger docs so that examples include the responses
- You should have …

AP-3571: Update section 8 tasks seed

---

db/seed_data/proceeding_type_merits_task.yml

This question has traditionally been displayed on all applications because they all had a DA proceeding where the client was an applicant.
That rule, and limitation, is changing and it is not required _at all_ for non Domestic Abuse proceedings …

Fix: Remove latest_incident from non Domestic Abuse proceedings

---

app/services/merits_task_service.rb
app/services/questions_service.rb
db/seed_data/proceeding_type_merits_task.yml
spec/services/questions_service_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-3591)
This updates the logic and redefines the name for clarity 
It also updates the manual reference in the original merits task service to ensure it obeys the same exclusion rules
- You should have checked that the commit messages say …

AP-3591: Update display_rule for latest_incident_details question

---

db/populators/merits_task_populator.rb
db/seed_data/proceeding_type_merits_task.yml

Replace reasons_for_new_application vary_order merits_task and proceeding_type_merits_task
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3489)
Rename reason_for_new_application --> vary_order
as from discussion between JS and CB it was agreed that
the name of the merits task is more clearly and concisely
covered by vary_order.
This name is to be used by Apply as well for the merits
question logic - see https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull/4518
- The PR …

AP-3489 replace reason_for_new_application with vary_order merits_task

---

db/populators/merits_task_populator.rb
db/seed_data/proceeding_type_merits_task.yml
spec/models/merits_task_spec.rb
spec/models/proceeding_type_spec.rb
spec/requests/civil_merits_questions_controller_swagger_spec.rb
spec/requests/merits_tasks_controller_swagger_spec.rb
spec/services/merits_task_service_spec.rb
spec/services/questions_service_spec.rb
swagger/v1/swagger.yaml

[Link to story](https://dsdmoj.atlassian.net/browse/AP-3593)
Update the seed data for merits tasks to replace opponent_deatils with three discrete questions
Ensure the task lists per proceeding type are updated to reflect the new options for DA and Child Section 8
- You should have checked …

AP-3593: Split opponent questions

---

.github/workflows/delete-uat-release.yml

Bump github action for delete-uat-release from v1.0.0 to use v1.0.1
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3669)
[delete uat release GHA v1.0.1](https://github.com/ministryofjustice/laa-civil-apply-delete-uat-release/releases/tag/v1.0.1)
see [github action bump PR](https://github.com/ministryofjustice/laa-civil-apply-delete-uat-release/pull/2) for more details.
see [successful test deletion with no deprecation warnings](https://github.com/ministryofjustice/legal-framework-api/actions/runs/3582656827/jobs/6027140022)
- There should be no unnecessary whitespace changes. These make diffs …

Bump github action delete-uat-release v1.0.1

---

.circleci/config.yml
config/environments/test.rb

Before, the code was eager loaded every time a test was run.
When you're running a single test, this doesn't make much sense.
This updates the test configuration to eager load only when the `CI` environment
variable is set (i.e default Rails behaviour).

Only eager load Ruby code when running tests in CI

---

.github/workflows/codeql-analysis.yml
.github/workflows/docker-image-scan.yml

This PR:
* Updates all CodeQL actions to v2 as v1 is due to be deprecated on Jan 18th 2023
* Updates all checkout actions to v3 as v2 uses node12 which has also been deprecated

Fix: Update the github action versions

---

db/seed_data/matter_types.yml

This removes TODO comments suggesting matter type seed data names are renamed, and replaces them with a ticket to track the work in JIRA.
[Link to new story](https://dsdmoj.atlassian.net/browse/AP-3732)
[AP-3732]: https://dsdmoj.atlassian.net/browse/AP-3732?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove TODO comment

---

app/models/proceeding_type.rb
app/services/proceeding_type_populator.rb
db/populators/default_cost_limitation_populator.rb
db/seed_data/default_cost_limitations.yml
spec/models/proceeding_type_spec.rb
spec/populators/default_cost_limitation_populator_spec.rb
spec/services/proceeding_type_service_spec.rb

Create a new populator for default cost limitations.
It reads from a new seed file and creates default cost limits with a default set of values that get overridden if a separate yaml
block exists for a given proceeding type
It removes the old seeding method that was included in ProceedingTypePopulator
It tidies up some existing tests that were failing because the default values changed
This is a new method of seeding (one default set and then overrides) so I'm interested to see what people think.
I did it this way to remove some of the repetition in the other seed files
Happy to discuss, pair and update if needed
- Github should not …

AP-3749: Update s8 substantive cost limit seeding

---

.circleci/config.yml
bin/delete_ecr_images
bin/uat_deploy

Use short lived credentials (IRSA) for ECR push
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4298)
Following the guide from cloud platform [migrating to short lived credentials for CircleCi](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/container-repositories/deprecating-long-lived-credentials.html#migrating-to-short-lived-credentials-for-circleci).
See related PR for [Adding CircleCI OIDC provider](https://github.com/ministryofjustice/cloud-platform-environments/pull/14437)
Note, since the `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`
and `AWS_DEFAULT_REGION` still exist in the circleci environment
variables it is unclear whether they are being used.
A test on Hmrc Interface was successfull in this [CircleCI …

AP-4298: Use short lived credentials (IRSA) for ECR push

---

README.md
app/controllers/organisation_types_controller.rb
app/models/organisation_type.rb
config/routes.rb
spec/factories/organisation_types.rb
spec/models/organisation_type_spec.rb
spec/requests/organisation_types_controller_swagger_spec.rb
swagger/v1/swagger.yaml

Add new endpoint to retrieve all organisation types
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4281)
So organisation types can be retrieved for use in Apply front-end (descriptions)
and for CCMS injection (ccms_code).
- remove reference to non-existent folder `spec/requests/swagger_docs`
- Add endpoint
- Add request spec and use to update swagger doc for endpoint
- You should have looked at …

AP-4281: Add opponent organisation endpoint

---

app/services/organisation_full_text_search.rb
spec/requests/organisations_controller_swagger_spec.rb
swagger/v1/swagger.yaml

Add org name and type highlighted "headlines" to response
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4455)
Can be used to construct the search results with highlighting
built in. javascript/front-end changes required by consumer.
See [related PR](https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull/5782) that consumes the "headlines" 
- You should have looked at the diff against …

AP-4455: Add full text search "headlines" output to search endpoint

---

.github/dependabot.yml

These always seem to update in a group and it will save time and resources to merge as one

Chore: Add RSwag dependabot group

---

bin/delete_dependabot_deployment

Delete PVCs in dependabot delete deployment script
Not deleted by helm delete so needed in script explicitly. 
PVCs eat up resource and cost in the cluster, particualry 
backups apparently. Raised and requested by CP.
- You should have checked that the commit messages say why the change was …

Delete PVCs in dependabot delete deployment script

---

.circleci/config.yml

Migrate from 'deploy' to 'run' for deploy step on uat, staging and production
- You should have checked that the commit messages say …

Chore: Migrate deprecated deploy circle ci step

---

.github/workflows/codeql-analysis.yml
.github/workflows/delete-uat-release.yml

Bump versions to remove node warnings

Chore: Update github action versions

---

.circleci/config.yml

This has started to regularly fail and other circle rubocop calls use `bundle exec` rather than `bin/rails`
- You should have …

Chore: Update circle rubocop invocation

---

.circleci/config.yml

The build_and_push ci step was failing with the error "This job was rejected because the image is [unavailable]" due to us using a deprecated version of remote docker and a "brownout" documented here https://discuss.circleci.com/t/remote-docker-image-deprecations-and-eol-for-2024/50176. 
This pr updates circleci config to use the default/latest stable version of remote docker
- There should be no unnecessary whitespace changes. These make diffs …

Use default/latest stable version of remote docker

---

README.md
app/controllers/countries_controller.rb
app/models/country.rb
app/services/countries_full_text_search.rb
config/routes.rb
db/migrate/20240314132923_add_searchable_to_country.rb
db/schema.rb
db/seeds.rb
spec/requests/countries_controller_swagger_spec.rb
spec/services/countries_full_text_search_spec.rb
swagger/v1/swagger.yaml

[Link to story](https://dsdmoj.atlassian.net/browse/AP-4851)
Add a new, countries/search, endpoint with fuzzy logic for matching country names
Update after initial commit:
This now extracts the generation of the searchable (tsvector) text from the migration to the Country model (the same as the ProceedingType, rather than organisation)
This will allow us to re-generate the searchable text if we update the values in the seed file.  The original version would only generate it when the migration ran and would never get updated afterwards 
- The standards in the [Git Workflow document on …

AP-4851: Add country search with fuzzy logic

---

.circleci/config.yml

- Bump CircleCI aws-cli from 4.0.0 to 4.1.3
- Bump CircleCI slack from 4.5.2 to 4.13.2 …

Chore: Update CircleCI orbs

---

.circleci/config.yml

This aims to update the flow to be similar for all services.
If both deploys succeed, it sends the message to slack and allows the hold to be released. This means that when deploying in a hurry, emergency fixes, etc; and you are waiting to deploy you are not blocked waiting for the the slack message to be sent.
It also means that if slack is offline for any reason it does not block deploys
- There should be no unnecessary whitespace changes. …

Chore: Update circle flow

---

app/models/default_cost_limitation.rb

Changes to Rails mean that enums should use a new pattern 
In 7.2 they started adding deprecation warnings, in 8+ they will stop working.  
This PR updates to the new pattern and should reduce issues with future Rails updates
- You should have …

Chore: Enum updates

---

app/controllers/proceeding_types/filter_controller.rb
app/models/proceeding_type.rb
app/services/proceeding_type_filter.rb
app/services/proceeding_type_full_text_search.rb
config/routes.rb
spec/models/proceeding_type_spec.rb
spec/requests/proceeding_types/filter_controller_swagger_spec.rb
spec/requests/proceeding_types/searches_controller_swagger_spec.rb
spec/services/proceeding_type_filter_spec.rb
swagger/v1/swagger.yaml

[Link to story](https://dsdmoj.atlassian.net/browse/AP-5235)
This adds a new ProceedingType endpoint, `filter` that accepts three optional parameters, `current_proceedings`, `allowed_categories`, and `search_term`
This allows us to remove proceeding types that do not comply with the rules set by the SCA requirements, e.g. 
* only show SCA core proceedings to start
* if user has already picked a non-SCA proceeding, show no SCA proceedings
* if a user has picked an SCA core proceeding, only show SCA core and related
It also includes options for categories and search text to allow us to extend the apply use to limit the categories of law that an individual provider is contractually supposed to see and restrict answers to proceedings with certain text
This _may_ allow us to remove some …

AP-5235: SCA proceeding search

---

db/migrate/20240912082030_add_index_to_matter_types.rb
db/populators/matter_type_populator.rb
db/populators/threshold_waiver_populator.rb
db/schema.rb
db/seed_data/threshold_waivers.json

[Link to story](https://dsdmoj.atlassian.net/browse/AP-5304)
Update populators to match against ccms code rather than name as code will not change in the future, but name could do
Add index back onto `MatterType` table against `code` rather than `name`
- The PR description should say what you changed and why, with a link to the JIRA …

AP-5304: Update LFA to deal with proceeding name changes

---

deploy/helm/templates/_envs.tpl
deploy/helm/templates/secret.yaml

Remove UAT database name from secrets
[Came out of similar on hmrc interface api work](https://dsdmoj.atlassian.net/browse/AP-5157)
This value is not a secret and is already exposed in the values-uat file
in any event. This is inline with hmrc interface'es handling
- The PR description should say what you changed and why, with a link …

Remove UAT database name from secrets

---

deploy/helm/templates/_envs.tpl
deploy/helm/templates/secret.yaml

Remove deployHost from old k8s secret
This is just an ingress that is visible in the Values
files and cloud-platform-environments in any event.
This removes the last secret and therefore means we no longer
need the old k8s secret at all.
It brings LFA in line with HMRC interface as well.
- There should be no unnecessary whitespace changes. These make diffs harder to read and conflicts …

AP-5157: Remove deployHost secret

---

.simplecov
README.md
spec/requests/client_involvement_types_controller_swagger_spec.rb
swagger/v1/swagger.yaml

Add tests for client involvment type controller
To achieve 100% line coverage. There is still below 100% branch coverage.
- You should have looked at the diff against main and ensured …

Fix: add tests to achieve 100% line coverage

---

db/seed_data/proceeding_types.yml
spec/requests/proceeding_types/searches_controller_swagger_spec.rb
spec/services/proceeding_type_full_text_search_spec.rb
swagger/v1/swagger.yaml

Correct PBM40E proceeding type meaning
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5377)
A second, repeated, set of key value pairs overwrote the first with
the wrong values. Tests then enforced the invalid values.
- You should have …

Fix: Correct PBM40E proceeding type and tests

---

app/services/proceeding_type_filter.rb
spec/services/proceeding_type_filter_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-4410)
Filter PLF proceedings - once a user has selected a PLF proceeding, all other matter types should be removed from the filtered return data set
- You should have looked at the diff …

AP-4410: Add test for PLF filtering

---

app/controllers/status_controller.rb
spec/requests/status_spec.rb

Amend /status endpoint to use database_exists?
[Identified while working on ticket](https://dsdmoj.atlassian.net/browse/AP-5668)
Inline with hmrc-interface app, at least, and best
practice since rails 7.2 as `active?` may be false
due to lazy loaded connections
- The PR description should say what you changed and why, with a link to …

Chore: Amend /status endpoint to use database_exists?

---

Dockerfile

When deploying a new dependabot, the build step failed because psych could not find the yaml files needed to compile.  This PR adds yaml-dev as a temporary package so that psych can compile and then removes it with the other build dependencies
- …

Fix: Fix build step issue

---

app/models/proceeding_type.rb
config/environments/test.rb
lib/tasks/fixes/ap_5603.rake
spec/lib/tasks/fixes_spec.rb

Remove unused proceeding SE099E
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5603)
It was removed 9 September 2024. [commit here](https://github.com/ministryofjustice/legal-framework-api/pull/1419/commits/f61f9d4bd51e67c6fc197361487ef3768dbcf515) but is still in the database on main uat, staging and production.
I identified some no longer existing relations to the table and model, `proceeding_type_scope_limitations`, which was deleted 2 years ago. These have been removed in a separate commit.
- The standards in the [Git Workflow document on …

AP-5603: Remove unused proceeding SE099E

---

lib/tasks/fixes/ap_5603.rake

Fix typs in rake task
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5603) …

AP-5603: fix typos in rake task

---

app/services/proceeding_type_filter.rb
spec/services/proceeding_type_filter_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-5727)
When a non PLF proceeding is present, no PLF proceedings should be returned.  
This is in addition to the means/non-means PLF filtering already in place
- You should have looked at the …

AP-5727: Update proceeding type filter 

---

db/seed_data/proceeding_type_merits_task/public_law_family.yml
spec/services/questions_service_spec.rb

Replace PLF vary order merits task
[Leftover from story](https://dsdmoj.atlassian.net/browse/AP-4414)
Replace plf_vary_order merits tasks with existing vary_order merits
task and delete the plf_vary_order merits_task. 
It was originally thought that this question may be different from the same
question for different matter types. Design changed the question to be suitable
for any matter type and hence this merits_task has never been wired up in Civil Apply. 
> [!WARNING]  
> Without this change the PLF proceedings PBM05, 07 and 33 do not currently get the question added to their merits 
task list when they should.
Testing: The proceeding_merits_task_list join table records were destroyed by the removal of the relations. The merits_task has deliberately not been destroyed in this PR for …

Chore: Replace PLF vary order merits task

---

db/populators/merits_task_populator.rb
spec/populators/merits_task_populator_spec.rb

Delete plf_vary_order merits task
[Leftover from story](https://dsdmoj.atlassian.net/browse/AP-4414)
Following [the replacement PR](https://github.com/ministryofjustice/legal-framework-api/pull/1545) the `plf_vary_order` merits task is no longer associated with any proceedings. 
This was previously associated with proceedings PBM05, 07 and 33
but has since been replaced by the standard vary_order merits task. 
This is because designers have changed the content for the question 
in Civil Apply such that the standard question can be used for all 
applicable matter type proceedings.
- The standards in …

Chore: Delete unused plf_vary_order merits task

---

app/controllers/proceeding_types/filter_controller.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-5728)
Return a consistent result block
```ruby
{ success: true, data: [responses] }
```
and
```ruby
{ success: false, data: [] }
```
This should allow Civil Apply to expect a standard response rather than having to parse for empty arrays and text analysis
- The PR description …

AP-5728: Update proceeding_type/filter endpoint

---

deploy/helm/templates/ingress.yaml
deploy/helm/values-production.yaml
deploy/helm/values-staging.yaml
deploy/helm/values-uat.yaml

Change non-prod ingresses to default-non-prod class
Following recommendations from CP.
see https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/does-my-app-need-ingress.html#does-my-app-need-an-ingress
- You should …

Chore: Change non-prod ingresses to default-non-prod class

---

deploy/helm/values-staging.yaml

Currently, we turn off RDS at night for non prod environments but we don't have scheduled downtime for the pods. A PR is open to make the relevant changes to cloud platform environment here: https://github.com/ministryofjustice/cloud-platform-environments/pull/32690. This PR updates `values-staging` to add the relevant changes to this repo
- There should be no unnecessary whitespace changes. These make diffs harder to read and conflicts more …

Chore: update values-staging to add scheduled downtime

---

.circleci/config.yml

The CodeClimate quality checks were deprecated over the weekend, this PR removes the circle ci uploads
- You should have checked …

Chore: Remove CodeClimate from repo

---

Gemfile

Remove deprecated platforms tags
Handles this deprecation notice
```
[DEPRECATED] Platform :mingw, :x64_mingw is deprecated. Please use platform :windows instead.
```
- You should have looked at the diff against main and ensured that nothing …

Chore: Remove deprecated platforms tags
