ministryofjustice/legal-framework-api

.circleci/based-on-cfe-config.yml, .circleci/config.yml
Add lint checks and unit tests to the circl ci checks
=> New circle config

.circleci/config.yml, bin/uat_deploy
Refactor the build and push to ecr jobs.
Add workflow to require unit tests etc before deploying to uat
=> Refactor build and push to mirror CFE 

.circleci/config.yml, bin/delete_uat_release.sh
Deploy to master UAT and delete the current deployment from UAT environment
Also deploy to staging
=> Circle CI behaviour on Merge of PR

db/seed_data/proceeding_type_merits_task.yml, doc/apipie_examples.json, spec/requests/merits_tasks_spec.rb, spec/services/merits_task_service_spec.rb
Adds the attempt_to_settle task to the merits task list for Section 8 proceedings
=> AP-2263 add attempts to settle tasks

.github/dependabot.yml
We were not checking for npm updates
=> TechDebt: Update dependabot with npm

bin/uat_deploy_to_live
As noted by Mark the release-host should be the same for both live and live-1
- fix release host name
=> update release host

.circleci/config.yml, .rspec, spec/services/proceeding_type_full_text_search_spec.rb
Use the plain cimg/ruby:3.0.2-node images
=> AP-2645: Update CircleCI Docker images

.github/workflows/codeql-analysis.yml
Add a GitHub Action for CodeQL to scan the repo on all merges to `main`, all pull requests, and once a week.
=> AP-2693 Add CodeQL

.rubocop_todo.yml, app/controllers/merits_tasks_controller.rb, app/controllers/proceeding_types/searches_controller.rb, app/controllers/proceeding_types/threshold_waivers_controller.rb, app/controllers/proceeding_types_controller.rb, app/controllers/status_controller.rb, app/services/matter_type_populator.rb, app/services/merits_task_service.rb, app/services/proceeding_type_full_text_search.rb, app/services/proceeding_type_populator.rb, app/services/proceeding_type_service.rb, app/services/threshold_waiver_service.rb, db/populators/merits_task_populator.rb, db/populators/proceeding_type_merits_task_populator.rb, db/populators/proceeding_type_scope_limitations_populator.rb, db/populators/scope_limitations_populator.rb, db/populators/task_dependency_populator.rb, spec/models/default_cost_limitation_spec.rb, spec/models/matter_type_spec.rb, spec/requests/proceeding_types/searches_spec.rb, spec/requests/proceeding_types/threshold_waivers_spec.rb, spec/requests/proceeding_types_spec.rb, spec/services/merits_task_service_spec.rb, spec/services/proceeding_type_full_text_search_spec.rb, spec/services/proceeding_type_service_spec.rb, spec/services/threshold_waiver_service_spec.rb
Initial batch of GOVUK rubocop fixes.
=> Fix rubocop todos

.rubocop_todo.yml, app/services/matter_type_populator.rb, app/services/proceeding_type_populator.rb, config/spring.rb, db/populators/scope_limitations_populator.rb, spec/models/default_cost_limitation_spec.rb, spec/models/merits_task_spec.rb, spec/models/proceeding_type_spec.rb, spec/requests/merits_tasks_spec.rb, spec/requests/proceeding_types/searches_spec.rb, spec/requests/proceeding_types/threshold_waivers_spec.rb, spec/requests/proceeding_types_spec.rb, spec/services/merits_task_service_spec.rb, spec/services/proceeding_type_full_text_search_spec.rb, spec/services/proceeding_type_populator_spec.rb, spec/services/proceeding_type_service_spec.rb, spec/services/threshold_waiver_service_spec.rb
Fixes more GOVUK rubocop offences.
=> More rubocop todos 

app/views/layouts/apipie_override.html.erb, app/views/layouts/mailer.html.erb
=> Fix errors flagged by erblint

.github/workflows/docker-image-scan.yml
Following documentation [here](https://github.com/snyk/actions), this creates a GitHub action to run a scheduled daily scan of the application's Docker image, and alert on the findings:
1) Build the Docker image
2) Scan the image with Snyk
3) Push the results to Snyk
4) Upload results to CodeQL for alerting in Github
- You should have looked at the diff against main and ensured that nothing unexpected is …
=> L&D: Enable Snyk Docker Image Scanning

docs/CODEOWNERS
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2983)
Adds a `CODEOWNERS` file requiring all pull requests be approved by a member of the `laa-apply-for-legal-aid` GitHub team.
=> AP-2983 Add CODEOWNERS file

.editorconfig, README.md, docs/development.md, spec/spec_helper.rb
Small changes to config and readme
- Add editor config file
- Allow for focused spec running
- Readme tweaks
=> Small changes from onboarding

Gemfile, Gemfile.lock, app/models/proceeding_type.rb, app/models/proceeding_type_service_level.rb, app/models/service_level.rb, db/migrate/20220504083530_create_service_levels.rb, db/migrate/20220504121754_create_proceeding_type_service_levels.rb, db/schema.rb, spec/factories/matter_types.rb, spec/factories/proceeding_type_service_levels.rb, spec/factories/proceeding_types.rb, spec/factories/service_levels.rb, spec/models/proceeding_type_spec.rb, spec/models/service_level_spec.rb, spec/rails_helper.rb
Create tables for storing service levels and their association to proceeding types
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3075)
Schema changes to store data to allows association of
one or more "levels of service" with a proceeding type.
- You should have checked that the …
=>  [AP-3075] create service levels (a.k.a levels of service)

Gemfile, Gemfile.lock, app/models/proceeding_type.rb, config/environments/test.rb, db/populators/proceeding_type_service_levels_populator.rb, db/populators/service_levels_populator.rb, db/seed_data/proceeding_type_service_levels.yml, db/seed_data/service_levels.yml, db/seeds.rb, spec/models/proceeding_type_spec.rb, spec/models/service_level_spec.rb, spec/populators/proceeding_type_service_levels_populator_spec.rb, spec/populators/scope_limitations_populator_spec.rb, spec/populators/service_levels_populator_spec.rb, spec/rails_helper.rb
Seed service levels and proceeding type service levels tables
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3076)
=> [AP-3076] seed service levels

.circleci/config.yml, bin/delete_dependabot_deployment
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2809)
Add a new step to circleci config to call delete script
Add delete script
=> AP-2809 add dependabot delete script and update config

.circleci/config.yml
remove duplicate line in circle config that sets the context
=> bugfix: remove duplicate line in circle config

app/controllers/client_involvement_types_controller.rb
The data returned wasn't properly converted to JSON
This matches the handling in the proceeding_types/all endpoint
=> Fix: client_involvement endpoint

app/controllers/client_involvement_types_controller.rb, app/models/client_involvement_type.rb, db/migrate/20220726071615_add_ordering_to_client_involvement_types.rb, db/populators/client_involvement_types_populator.rb, db/schema.rb, db/seed_data/client_involvement_types.yml, spec/factories/client_involvement_type.rb, spec/models/client_involvement_type_spec.rb, spec/requests/client_involvement_types_controller_spec.rb, spec/requests/swagger_docs/client_involvement_types_spec.rb, swagger/v1/swagger.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3353)
=> ap-3353: add ordering to client_involvement_type

app/models/scope_limitation.rb, db/populators/proceeding_type_scope_populator.rb, db/populators/scope_limitations_populator.rb, db/seed_data/proceeding_type_scopes.yml, db/seed_data/scope_limitations.yml, db/seeds.rb, spec/models/scope_limitation_spec.rb, spec/populators/scope_limitations_populator_spec.rb
This PR is to populate the proceeding_type_scopes table with the information we have so far.
This table is a. join table and will eventually replace the existing proceeding_types_scope_limtations table, which allows a many-to-many relationship between proceeding types and scope limitations.  However, the requirement will soon be to have a specific set of scope limitaions for each proceeding_type/client_involvement_type/service_level/substantive_or_df combination, and this new table is designed to handle that, as well as specify the default scope in each case.
The table is popualated by reading a specialised yaml file which specifies the details for each proceeding type.
This also necessitated adding 6 more scope limitations with the proceeding_type_scope records referred to (this will not …
=> AP-3357 Populate pt scopes

spec/models/default_cost_limitation_spec.rb, spec/models/matter_type_spec.rb, spec/models/merits_task_spec.rb, spec/models/proceeding_type_scope_spec.rb, spec/models/proceeding_type_spec.rb, spec/models/scope_limitation_spec.rb, spec/models/service_level_spec.rb, spec/populators/client_involvement_types_populator_spec.rb, spec/populators/proceeding_type_service_levels_populator_spec.rb, spec/populators/scope_limitations_populator_spec.rb, spec/populators/service_levels_populator_spec.rb, spec/rails_helper.rb, spec/requests/client_involvement_types_controller_spec.rb, spec/requests/merits_tasks_controller_spec.rb, spec/requests/proceeding_types/searches_spec.rb, spec/requests/proceeding_types/threshold_waivers_spec.rb, spec/requests/proceeding_types_spec.rb, spec/requests/swagger_docs/client_involvement_types_spec.rb, spec/requests/swagger_docs/merits_tasks_spec.rb, spec/requests/swagger_docs/new_threshold_waivers_spec.rb, spec/requests/swagger_docs/proceeding_type_searches_spec.rb, spec/requests/swagger_docs/proceeding_types_spec.rb, spec/requests/swagger_docs/threshold_waivers_spec.rb, spec/requests/threshold_waivers_controller_spec.rb, spec/services/merits_task_service_spec.rb, spec/services/proceeding_type_full_text_search_spec.rb, spec/services/proceeding_type_populator_spec.rb, spec/services/proceeding_type_service_spec.rb, spec/services/threshold_waiver_service_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3370)
- removed over 30 individual calls to `seed_live_data`
- called it once in a `before(:suite)` hook
Improved time from 7 minutes to 7 seconds.
=> AP-3370 Improve test suite times

app/models/proceeding_type.rb, app/services/proceeding_type_full_text_search.rb, app/services/proceeding_type_service.rb, app/services/threshold_waiver_service.rb, db/migrate/20220728101235_add_full_section8_to_proceeding_types.rb, db/schema.rb, spec/requests/proceeding_types/searches_spec.rb, spec/requests/proceeding_types/threshold_waivers_spec.rb, spec/requests/proceeding_types_spec.rb, spec/requests/threshold_waivers_controller_spec.rb, spec/services/proceeding_type_full_text_search_spec.rb, spec/services/proceeding_type_service_spec.rb, spec/services/threshold_waiver_service_spec.rb, swagger/v1/swagger.yaml
[Link to story](https://dsdmoj.atlassian.net/jira/software/c/projects/AP/boards/233?modal=detail&selectedIssue=AP-3362)
=> Ap 3362 add full section 8 to proceeding types

app/controllers/proceeding_type_defaults_controller.rb, app/services/proceeding_type_defaults_service.rb, config/routes.rb, spec/requests/proceeding_type_defaults_controller_spec.rb, spec/requests/swagger_docs/proceeding_type_defaults_spec.rb, spec/services/proceeding_type_defaults_service_spec.rb, swagger/v1/swagger.yaml
[Link to story](https://dsdmoj.atlassian.net/jira/software/c/projects/AP/boards/233?modal=detail&selectedIssue=AP-3350)
=> ap-3350: add proceeding_type_defaults endpoint

swagger/v1/swagger.yaml
The swagger docs were broken by https://github.com/ministryofjustice/legal-framework-api/pull/698. The release seeks to fix them.
=> Fix broken swagger docs

app/services/proceeding_type_populator.rb, db/seed_data/proceeding_types.yml, spec/requests/proceeding_types/searches_spec.rb, spec/services/proceeding_type_full_text_search_spec.rb, spec/services/proceeding_type_populator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3371)
- converted existing yaml seed file to use key-value pairs rather than positional parameters
- added new seed data
=> AP-3371 Populate ProceedingTypes with new section 8 proceedings

app/controllers/proceeding_type_defaults_controller.rb, app/services/proceeding_type_defaults_service.rb, spec/requests/proceeding_type_defaults_controller_spec.rb, spec/requests/swagger_docs/proceeding_type_defaults_spec.rb, spec/services/proceeding_type_defaults_service_spec.rb
[Link to story](https://dsdmoj.atlassian.net/jira/software/c/projects/AP/boards/233?modal=detail&selectedIssue=AP-3396)
=> Ap 3396 proceeding type defaults json schema

.circleci/config.yml, bin/delete_ecr_images
This should remove LFA from the CP alerts spreadsheet
=> Fix: Add an ECR cleanup job

.rubocop.yml, app/controllers/civil_merits_questions_controller.rb, app/models/merits_task.rb, app/services/merits_task_service.rb, app/services/questions_service.rb, config/routes.rb, db/migrate/20221010132246_add_display_rules_to_proceeding_type_merits_tasks.rb, db/populators/merits_task_populator.rb, db/populators/proceeding_type_merits_task_populator.rb, db/schema.rb, db/seed_data/proceeding_type_merits_task.yml, lib/tasks/swag.rake, public/schemas/civil_merits_questions.json.erb, spec/models/proceeding_type_spec.rb, spec/requests/civil_merits_questions_controller_swagger_spec.rb, spec/services/questions_service_spec.rb, swagger/v1/swagger.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3476)
This adds a new endpoint, named to avoid generic use/clashes with crime if they start using it, that returns an identical task list as the previous endpoint, but allows rules to be set for a proceeding depending on the Client Involvement Type and use of delegated functions
It also uses a new pattern for Swagger tests that allows us to have a single test that exercises the request(RSpec) tests as well as allowing swagger generation …
=> AP-3476: Extend merits task list questions

spec/requests/civil_merits_questions_controller_swagger_spec.rb
This text was recorded as a placeholder while debugging the structure, this is a more accurate description!
=> Fix: Update the swagger parameter description

Gemfile, Gemfile.lock
Bump rswag related dependencies
To allow us to deploy and test and combine several
dependency bumps in one.
=> Bump rswag dependencies

db/seed_data/proceeding_type_merits_task.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3658)
Added seed data for merits questions for new s8 proceeding types.
=> ap-3658: Update merits questions lists for new s8 proceedings

docs/development.md
Update the development.md document with 1Password details instead of LastPass since we no longer use LastPass. 
=> Update development.md from LastPass to 1Password

app/models/organisation_type.rb, db/migrate/20230712121234_create_organisation_types.rb, db/populators/organisation_types_populator.rb, db/schema.rb, db/seed_data/organisation_types.yml, db/seeds.rb, spec/populators/organisation_types_populator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4279)
Created organisation_types database table and model.
Seeded data.
=> Ap 4279 add organisation seed data

Gemfile.lock
Reverts ministryofjustice/legal-framework-api#996
```
Errors
Fetch error
Internal Server Error /api-docs/v1/swagger.yaml
```
=> Revert "build(deps): bump rswag-api from 2.9.0 to 2.10.1"

.simplecov, spec/populators/merits_task_populator_spec.rb, spec/populators/task_dependency_populator_spec.rb, spec/populators/threshold_waiver_populator_spec.rb, spec/spec_helper.rb
Amend coverage config and increase coverage
- Move simplecov config to centralised location and amend
for readabillity
- Add coverage for merits_task_populator
- Add coverage for task_dependency_populator
- Add coverage for threshold_waiver_populator …
=> Increase test coverage

spec/swagger_helper.rb, swagger/v1/swagger.yaml
Update API title & description
`LAA Legal Framework` instead of `API V1`
=> Update API title & description

docs/pull_request_template.md
Update pull request template to include git workflow
=> Docs: Update pull request template to include git workflow

Gemfile
There were a lot of comments and broken up chunks of gems, this moves them into single groups and alphabetises them
It is also a bellwether for checking the new Circle CI service Account tokens!
- You should have looked at the diff against main …
=> Fix: Re-sequence Gemfile

app/controllers/countries_controller.rb, app/models/country.rb, config/routes.rb, db/migrate/20240215115400_create_countries.rb, db/populators/countries_populator.rb, db/schema.rb, db/seed_data/ccms_countries.yml, db/seeds.rb, spec/factories/countries.rb, spec/models/country_spec.rb, spec/populators/countries_populator_spec.rb, spec/requests/countries_controller_swagger_spec.rb, swagger/v1/swagger.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4819)
Seeded db with list of countries from ccms and added endpoint.
I have excluded some of the countries that were in the list with no code/description obsolete.
- You should have looked at …
=> Ap 4819 seed countries data and create endpoint

db/populators/matter_type_populator.rb, db/seed_data/matter_types.yml
[Prep for AP-4662](https://dsdmoj.atlassian.net/browse/AP-4662)
We have migrated some of the seed data to this new style as it is easier for devs to read as the seed data increases in size
As we will be adding to the matter types I thought I would get a head start and ensure it gets underway
- The PR description should say what you …
=> Chore: Update MatterType seeds

Dockerfile
This should address busybox security warnings
=> Chore: Update Alpine to 3.20

app/services/questions_service.rb, db/populators/merits_task_populator.rb, db/seed_data/proceeding_type_merits_task.yml, spec/populators/merits_task_populator_spec.rb, spec/services/questions_service_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5113)
Add the SCA merits questions and rules required to filter
- You should …
=> AP-5113: Add sca merits questions

deploy/helm/templates/_envs.tpl
=> AP-5156: Update _envs to use AWS secret manager

.circleci/config.yml, README.md, docs/development.md
[Remove git-crypt](https://dsdmoj.atlassian.net/browse/AP-5160)
- Left over references from AP-5160
- You should have checked that …
=> AP-5160 Remove git-crypt (part 3)

db/seed_data/matter_types.yml, db/seed_data/proceeding_types.yml, spec/populators/default_cost_limitation_populator_spec.rb, spec/populators/matter_type_populator_spec.rb, spec/populators/proceeding_type_populator_spec.rb, spec/requests/proceeding_types/searches_controller_swagger_spec.rb, spec/services/proceeding_type_filter_spec.rb, spec/services/proceeding_type_full_text_search_spec.rb, swagger/v1/swagger.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5325)
- You should have checked that the …
=> Ap 5325 seed new plf proceedings

.github/workflows/dependabot-jira.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5409)
Update the prior condition of checking the PR user to checking the PR label and changed jira summary and description due to character limits within Jira
- You should have looked at the …
=> AP-5409: Change GHA gajira condition

db/seed_data/proceeding_types.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5464)
This was updated after the initial ticket was finalised
This ensures it matches the enforcement version
- You should have looked at the diff against main and ensured that nothing …
=> AP-5464: Update the PBM45 meaning

swagger/v1/swagger.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-6464)
This was updated as part of AP-5464 but the swagger update was missed
- …
=> Chore: Update PLF meaning in swagger docs

db/seed_data/proceeding_type_merits_task/public_law_family.yml, spec/services/questions_service_spec.rb
There is no need for a PLF specific version of this question
we can re-use the existing question now
- You should have checked that …
=> Fix: Update the PLF Specific Issue task name

db/seed_data/proceeding_type_merits_task/public_law_family.yml, spec/services/questions_service_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4305)
This was originally added as a defendant only question
After clarifying with caseworkers, the new question should be asked for _all_ client involvement types and the original question, opponents_application, should remain as defendant only
- The PR description should say …
=> AP-4305: Change PLF rules for Q6

db/populators/merits_task_populator.rb, db/seed_data/proceeding_type_merits_task/special_children_act.yml, spec/populators/merits_task_populator_spec.rb, spec/services/questions_service_spec.rb, swagger/v1/swagger.yaml
Move client_relationship_to_proceeding merits question from proceeding to ap…plication
This will allow us to ask the question once per child, rather than per proceeding which could result in inconsistent answers and conflicting data for CCMS submission
- The PR description …
=> AP-5580: Move client_relationship_to_proceeding merits question
